### ISSUE TITLE
Improve font, color, text, text style

### ISSUE THREAD

**Issue by madhurmehta007** [debz-g/YAWA-YetAnotherWeatherApp#3]
Use open source fonts which are free to use for project purposes. Keep the text color and style in accordance with Google's Material UI guidelines.

**Comment by Rishavgupta12345** [comment]
can I change the app icon to a cool one ???? BECAUSE it is using the old default one .

I am participating in KWOS so please ASSIGN me this issue so that i can contribute

@madhurmehta007 @debz-g

**Comment by Keshab0100** [comment]
I would like to do it

**Comment by debz-g** [comment]
@Rishavgupta12345 Also add some fonts and colours that matches material design too.

**Comment by Rishavgupta12345** [comment]
> @Rishavgupta12345 Also add some fonts and colours that matches material design too.

that will be a different pull request , I will do the rest part once you merge my first pull request #7 

Because the general rule of contribution suggests not to have many code changes and things done under a single pull request

**Comment by debz-g** [comment]
Yes the general rule suggest not to have many code changes, but just changing the app icon is a very minor code change.

**Comment by Rishavgupta12345** [comment]
> Yes the general rule suggest not to have many code changes, but just changing the app icon is a very minor code change.

ok will make few more commits to my pull request

**Comment by Rishavgupta12345** [comment]
> Yes the general rule suggest not to have many code changes, but just changing the app icon is a very minor code change.

now I did many changes check out my pull request #7

**Comment by debz-g** [comment]
Good work on removing the hardcoded strings and adding a little asthetics to the design @Rishavgupta12345 .

**Comment by Rishavgupta12345** [comment]
> Good work on removing the hardcoded strings and adding a little asthetics to the design @Rishavgupta12345 .

thanks, I have completed two pull request in total , is my KWOC over ?
